server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_agent?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0      # 使用的数据库索引
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数
          max-idle: 8     # 连接池最大空闲连接数
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  ai:
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7
          max-tokens: 16384
      embedding:
        options:
          model: embedding-3
          dimensions: 256
    vectorstore:
      redis:
        initialize-schema: true
        index: "ai_agent_rag_index:"
        prefix: "ai_agent_rag_prefix:"
    mcp:
      client:
        sse:
          connections:
            logistics-server:
              url: http://localhost:8888

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml

tavily:
  api-key: ${TAVILY_API_KEY}
  endpoint: https://api.tavily.com/search

ai:
  compress:
    max-tokens: 128000      # 模型上下文限制
    ratio: 0.5              # 硬阈值比例（max_tokens × ratio）
    target-ratio: 0.25      # 异步压缩目标比例（再压到阈值的一半）
    summary-ratio: 0.1      # 摘要文字数的比例

logging:
  level:
    com.tenny: debug
    org.springframework.ai: debug
    com.alibaba.cloud.ai.graph.executor.NodeExecutor: WARN